version: '3'
services:
  web:
    restart: always
    build: .
    expose:
      - "8080"
    volumes:
      - /app/static
  redis:
    image: "redis"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"